### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by SirLennox** [CorruptedBytes/DiscordGriefBot#3]
It seems like the LoginPacket has no use because you can send each other packet without logging in.

**Comment by CorruptedBytes** [comment]
The login system has been removed in the latest version (v5.4.2)
This vulnerability therefore no longer exists.

**Comment by SirLennox** [comment]
Removing a feature to "fix" a vulnerability, never saw such abstract solution for fixing something.

**Comment by CorruptedBytes** [comment]
> Removing a feature to "fix" a vulnerability, never saw such abstract solution for fixing something.

I never said I "fixed" it.
I said the feature was removed.
